datadir: /datos/ot/diana/llrc
xenadir: xena
tissues:
- name: bladder
  tcgat: blca
- name: brain
  normal: Brain - Cortex
  cancer: Brain Lower Grade Glioma
  tcgat: lgg
- name: breast
  tcgat: brca
- name: colon
  normal: Colon - Transverse 
  cancer: Colon Adenocarcinoma
  tcgat: coad
- name: esophagus
  normal: Esophagus - Mucosa
  cancer: Esophageal Carcinoma
  tcgat: none
- name: kidney
  tcgat: kirc
- name: liver
  normal: Liver
  cancer: Liver Hepatocellular Carcinoma
  tcgat: lihc
- name: lung
  tcgat: lusc
- name: ovary
  normal: Ovary
  cancer: Ovarian Serous Cystadenocarcinoma
  tcgat: ov
- name: pancreas
  normal: Pancreas
  cancer: Pancreatic Adenocarcinoma
  tcgat: none
- name: prostate
  normal: Prostate
  cancer: Prostate Adenocarcinoma
  tcgat: prad
- name: skin
  normal: Skin - Not Sun Exposed (Suprapubic)
  cancer: Skin Cutaneous Melanoma
  tcgat: skcm
- name: testis 
# No normal
  normal: Testis
  cancer: Testicular Germ Cell Tumor
  tcgat: none
- name: thyroid
  tcgat: thca
- name: uterus
  tcgat: ucec
xena: [colon, skin, pancreas, esophagus, liver, brain, ovary, testis, prostate]
new_annot: /home/dgarcia/Workspace/llrc/input/gencode.v44.annotation.gtf.gz
gdc_annot: /home/dgarcia/Workspace/llrc/input/gencode.v36.annotation.gtf.gz
# Aracne image from: https://github.com/ddiannae/ARACNE-multicore
aracne_singularity: /home/dgarcia/Workspace/aracne-singularity/aracne_multicore.sif
end: ascat
biomart: /home/dgarcia/Workspace/llrc-pipeline/input/Biomart_Ensembl102_GRCh38_p13.txt

