datadir: /datos/ot/diana/regulacion-trans
xenadir: xena
tissues:
- name: bladder
  step1: gc-upper
  step2: length-full
  step3: tmm
- name: brain
  normal: Brain - Cortex
  cancer: Brain Lower Grade Glioma
  step1: gc-upper
  step2: length-full
  step3: tmm
- name: breast
  step1: gc-upper
  step2: length-no
  step3: tmm
- name: colon
  normal: Colon - Transverse 
  cancer: Colon Adenocarcinoma
  step1: gc-upper
  step2: length-upper
  step3: tmm
- name: esophagus
  normal: Esophagus - Mucosa
  cancer: Esophageal Carcinoma
  step1: gc-upper
  step2: length-full
  step3: tmm
- name: kidney
  step1: gc-upper
  step2: length-no
  step3: tmm
- name: liver
  normal: Liver
  cancer: Liver Hepatocellular Carcinoma
  step1: gc-median
  step2: length-full
  step3: tmm
- name: lung
  step1: length-full
  step2: gc-median
  step3: tmm
- name: ovary
  normal: Ovary
  cancer: Ovarian Serous Cystadenocarcinoma
  step1: gc-full
  step2: length-full
  step3: tmm
- name: pancreas
  normal: Pancreas
  cancer: Pancreatic Adenocarcinoma
  step1: gc-upper
  step2: length-median
  step3: tmm
- name: prostate
  normal: Prostate
  cancer: Prostate Adenocarcinoma
  step1: gc-upper
  step2: length-median
  step3: tmm
- name: skin
  normal: Skin - Not Sun Exposed (Suprapubic)
  cancer: Skin Cutaneous Melanoma
  step1: gc-upper
  step2: length-full
  step3: tmm
- name: testis
  normal: Testis
  cancer: Testicular Germ Cell Tumor
  step1: gc-upper
  step2: length-full
  step3: tmm
- name: thyroid
  step1: gc-full
  step2: length-full
  step3: tmm
- name: uterus
  step1: gc-full
  step2: length-no
  step3: tmm
xena: [colon, skin, pancreas, esophagus, liver, brain, ovary, testis, prostate]
# Aracne image from: https://github.com/ddiannae/ARACNE-multicore
aracne_singularity: /home/dgarcia/Workspace/aracne-singularity/aracne.sif
end: "deg"
