datadir: /datos/ot/diana/regulacion-trans
xenadir: xena
#bladder, brain, breast, colorectal, esophagus, kidney, liver, lung, pancreas, prostate, skin, thyroid, uterus
tissues: [uterus]
xena_tissues: 
- name: skin
  normal: Skin - Not Sun Exposed (Suprapubic)
  cancer: Skin Cutaneous Melanoma
xena: [skin, pancreas, esophagus, brain, ovary, testis]
mccores: 78
# Aracne image from: https://github.com/ddiannae/ARACNE-multicore
aracne_singularity: /home/dgarcia/Workspace/aracne-singularity/aracne.sif
